import type { NextPage } from 'next'
import React, { ReactChildren, ReactChild } from 'react';
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'
import Events from './components/events'

const Home: NextPage = ({data}: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Viðburðakerfi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Viðburðir á næstunni</h1>
        <div className={styles.userContainer}>
          <Link href='/users/new'>
            <a>Nýskráning</a>
          </Link>
          <Link href='/users/login'>
            <a>Innskráning</a>
          </Link>
        </div>
        <Events e={data.items}/>
      
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://vef2-20222-v3-synilausn.herokuapp.com/events`)
  const data = await res.json()
  // Pass data to the page via props
  return { props: { data } }
}

export default Home
