import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Test: NextPage = ({data}) => {
  return(
	 <div className={styles.container}>
     <Head>
       <title>Create Next App</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </Head>
    	<main className={styles.main}>
    	{data.items.map((item) => (
        <p>{item.name}</p>
      ))}
    	</main>
   </div>
  )
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://vef2-20222-v3-synilausn.herokuapp.com/events`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}

export default Test